version: "3.9"

networks:
    dock_inter:
        external: true
        name: dock_inter
        
services:
  plex:
    image: lscr.io/linuxserver/plex
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/docker_data/Plex:/config
      - /dev/dri/renderD128:/dev/dri/renderD128:ro
      - /nfs/Media/tv:/tv
      - /nfs/Media/Movies:/movies
  
    networks:
      - dock_inter
